[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"

[dev]
  command = "npm run start"
  publish = "dist"
  targetPort = 8080

[[redirects]]
  from = "/"
  to = "https://stupidgoodcoffee.square.site"
  status = 302

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/hours-and-directions"
  to = "/hours"