[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"

[dev]
  command = "npm run start"
  publish = "dist"
  targetPort = 8080
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/hours-and-directions"
  to = "/hours"
  
[[redirects]]
  from = "/beans"
  to = "https://stupidgoodcoffee.square.site/product/coffee/108"

[[redirects]]
  from = "/gift"
  to = "https://stupidgoodcoffee.square.site/s/gift-cards"

[[redirects]]
  from = "/menu"
  to = "https://stupidgoodcoffee.square.site/s/order"
